### ISSUE TITLE
Linux permissions

### ISSUE THREAD

**Issue by dnk-codes** [Pwnyboy1031/SuperAutoPets-Bot#1]
Seems to bug out a bit, cannot recognize things
`Starting.....Go
The current gold count is 0
[ WARN:0@17.786] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('fish.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "SuperAutoPets Bot.py", line 417, in <module>
    main()
  File "SuperAutoPets Bot.py", line 411, in main
    chooseNextAction()
  File "SuperAutoPets Bot.py", line 264, in chooseNextAction
    update()
  File "SuperAutoPets Bot.py", line 60, in update
    identifyTeam()
  File "SuperAutoPets Bot.py", line 233, in identifyTeam
    Squad.append(identifyPet(x,teamy))
  File "SuperAutoPets Bot.py", line 222, in identifyPet
    if pyautogui.locateCenterOnScreen(pet + ".png", confidence=.40, region=(x,y, 200,250)) != None:
  File "/home/daniel/.local/lib/python3.8/site-packages/pyautogui/__init__.py", line 175, in wrapper
    return wrappedFunction(*args, **kwargs)
  File "/home/daniel/.local/lib/python3.8/site-packages/pyautogui/__init__.py", line 207, in locateCenterOnScreen
    return pyscreeze.locateCenterOnScreen(*args, **kwargs)
  File "/home/daniel/.local/lib/python3.8/site-packages/pyscreeze/__init__.py", line 413, in locateCenterOnScreen
    coords = locateOnScreen(image, **kwargs)
  File "/home/daniel/.local/lib/python3.8/site-packages/pyscreeze/__init__.py", line 373, in locateOnScreen
    retVal = locate(image, screenshotIm, **kwargs)
  File "/home/daniel/.local/lib/python3.8/site-packages/pyscreeze/__init__.py", line 353, in locate
    points = tuple(locateAll(needleImage, haystackImage, **kwargs))
  File "/home/daniel/.local/lib/python3.8/site-packages/pyscreeze/__init__.py", line 207, in _locateAll_opencv
    needleImage = _load_cv2(needleImage, grayscale)
  File "/home/daniel/.local/lib/python3.8/site-packages/pyscreeze/__init__.py", line 170, in _load_cv2
    raise IOError("Failed to read %s because file is missing, "
OSError: Failed to read fish.png because file is missing, has improper permissions, or is an unsupported or invalid format
`

**Comment by dnk-codes** [comment]
The error occurs her
`while pyautogui.locateCenterOnScreen("gameover.png") == None:`

**Comment by Pwnyboy1031** [comment]
Hi, did you get any functionality at all? This should only work on a display with the same resolution as mine. I haven't gone back and implemented usability for other resolutions because well, I didn't think anyone else would be using it! I'll look into that soon.

**Comment by aaaaaaaaaaaaaaaaadd22** [comment]
Whats the resolution?

**Comment by dnk-codes** [comment]
> Whats the resolution?

I believe I was running 1080p but I tried it with widnowed mode aswell using different resolutions.

**Comment by Pwnyboy1031** [comment]
I've only ever tested this on windows. Couldn't honestly tell you how it would run on linux.

**Comment by dnk-codes** [comment]
No worries
